version: 2
jobs:
  build:
    docker:
      - image: tianon/latex
    steps:
      - checkout
      - run:
          name: LaTeX build
          command: make pdf
      - store_artifacts:
          path: resume.pdf
